-- Lookup table first (referenced by BATCH)
CREATE TABLE batch_status (
    status_code   VARCHAR2(20) PRIMARY KEY,
    description   VARCHAR2(100)
);

CREATE TABLE equipment (
    equipment_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipment_name  VARCHAR2(50) NOT NULL,
    area            VARCHAR2(50),
    status          VARCHAR2(20) DEFAULT 'STOPPED',
    last_updated    TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE batch (
    batch_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_number   VARCHAR2(30) NOT NULL,
    product_code   VARCHAR2(30),
    start_time     TIMESTAMP,
    end_time       TIMESTAMP,
    status         VARCHAR2(20) DEFAULT 'PLANNED',
    equipment_id   NUMBER,
    CONSTRAINT fk_batch_equipment FOREIGN KEY (equipment_id) REFERENCES equipment(equipment_id),
    CONSTRAINT fk_batch_status FOREIGN KEY (status) REFERENCES batch_status(status_code)
);

CREATE TABLE production_event (
    event_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id         NUMBER,
    equipment_id     NUMBER,
    event_type       VARCHAR2(30),
    event_timestamp  TIMESTAMP DEFAULT SYSTIMESTAMP,
    description      VARCHAR2(200),
    severity         VARCHAR2(20) DEFAULT 'INFO',
    CONSTRAINT fk_event_batch FOREIGN KEY (batch_id) REFERENCES batch(batch_id),
    CONSTRAINT fk_event_equipment FOREIGN KEY (equipment_id) REFERENCES equipment(equipment_id)
);

CREATE TABLE audit_event (
    audit_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_timestamp  TIMESTAMP DEFAULT SYSTIMESTAMP,
    event_type       VARCHAR2(30),
    user_id          VARCHAR2(30),
    description      VARCHAR2(200)
);